apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ai-it-ops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "ai-it-ops"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "ai-it-ops-api.ai-it-ops.svc.cluster.local:8000"
