apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsguard.fullname" . }}-data
  labels:
    {{- include "opsguard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
